SELECT BSTOP, BLA, BLO, ESTOP, ELO,ELA, ISNULL(M,0) M,ISNULL(N,0) N,ISNULL(E,0) E,ISNULL(G,0) G FROM
(
SELECT DAYPART, BSTOP, BLA, BLO, ESTOP, ELO,ELA, SUM(AMOUNT)/5.0 as AMOUNT FROM
(
SELECT DAYPART, BSTOP, BLA, BLO, ESTOP, ELO,ELA, AMOUNT FROM
(
SELECT DAYPART, BCITY as BSTOP, LA as BLA, LO as BLO, ESTOP,ECITY,ELA,ELO, AMOUNT from 
(
SELECT DAYPART,b.STOP_NAME as BSTOP,b.CITY_NUMBER as BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO, AMOUNT FROM (
SELECT DAYPART,b.ID as BID, c.ID as EID, AMOUNT, 
ROW_NUMBER() OVER(PARTITION BY DAYPART,BGN,EGN ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE) + (b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG FROM
(SELECT DAYPART,BGN,EGN,SUM(AMOUNT) AMOUNT FROM ULTIMATE_TRANSACT_AGG
where DMON=4 AND DDAY>=3 AND DDAY<=7 group by DAYPART,BGN,EGN) a
join ULTIMATE_STOPS b on (a.BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (a.EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (b.id=BID)
join ULTIMATE_STOPS c on (c.ID=EID)
where RANG=1
) x join
(SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS GROUP BY CITY_NUMBER) y
on (x.BCITY like y.CITY_NUMBER)
WHERE BCITY not like ''
UNION ALL
SELECT DAYPART, BSTOP, BLA, BLO, ESTOP,ECITY,ELO,ELA, AMOUNT from 
(
SELECT DAYPART,b.STOP_NAME as BSTOP,b.CITY_NUMBER as BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO, AMOUNT FROM (
SELECT DAYPART,b.ID as BID, c.ID as EID, AMOUNT, 
ROW_NUMBER() OVER(PARTITION BY DAYPART,BGN,EGN ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE) + (b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG FROM
(SELECT DAYPART,BGN,EGN,SUM(AMOUNT) AMOUNT FROM ULTIMATE_TRANSACT_AGG
where DMON=4 AND DDAY>=3 AND DDAY<=7 group by DAYPART,BGN,EGN) a
join ULTIMATE_STOPS b on (a.BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (a.EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (b.id=BID)
join ULTIMATE_STOPS c on (c.ID=EID)
where RANG=1
) x WHERE BCITY like ''
) x WHERE ECITY like ''
UNION ALL
SELECT DAYPART, BSTOP, BLA, BLO, ECITY as ESTOP, La as ELA,LO as ELO, AMOUNT FROM
(
SELECT DAYPART, BCITY as BSTOP, LA as BLA, LO as BLO, ESTOP,ECITY,ELO,ELA, AMOUNT from 
(
SELECT DAYPART,b.STOP_NAME as BSTOP,b.CITY_NUMBER as BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO, AMOUNT FROM (
SELECT DAYPART,b.ID as BID, c.ID as EID, AMOUNT, 
ROW_NUMBER() OVER(PARTITION BY DAYPART,BGN,EGN ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE) + (b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG FROM
(SELECT DAYPART,BGN,EGN,SUM(AMOUNT) AMOUNT FROM ULTIMATE_TRANSACT_AGG
where DMON=4 AND DDAY>=3 AND DDAY<=7 group by DAYPART,BGN,EGN) a
join ULTIMATE_STOPS b on (a.BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (a.EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (b.id=BID)
join ULTIMATE_STOPS c on (c.ID=EID)
where RANG=1
) x join
(SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS GROUP BY CITY_NUMBER) y
on (x.BCITY like y.CITY_NUMBER)
WHERE BCITY not like ''
UNION ALL
SELECT DAYPART, BSTOP, BLA, BLO, ESTOP,ECITY,ELO,ELA, AMOUNT from 
(
SELECT DAYPART,b.STOP_NAME as BSTOP,b.CITY_NUMBER as BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO, AMOUNT FROM (
SELECT DAYPART,b.ID as BID, c.ID as EID, AMOUNT, 
ROW_NUMBER() OVER(PARTITION BY DAYPART,BGN,EGN ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE) + (b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG FROM
(SELECT DAYPART,BGN,EGN,SUM(AMOUNT) AMOUNT FROM ULTIMATE_TRANSACT_AGG
where DMON=4 AND DDAY>=3 AND DDAY<=7 group by DAYPART,BGN,EGN) a
join ULTIMATE_STOPS b on (a.BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (a.EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (b.id=BID)
join ULTIMATE_STOPS c on (c.ID=EID)
where RANG=1
) x WHERE BCITY like ''
) x join
(SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS GROUP BY CITY_NUMBER) y
on (x.ECITY like y.CITY_NUMBER)
WHERE ECITY not like ''
) x group by DAYPART, BSTOP, BLA, BLO, ESTOP, ELO,ELA
)x
PIVOT
(
SUM(AMOUNT)
FOR DAYPART in (M,N,E,G)
)y