SELECT ROUTE_NAME,BSTOP,BLA,BLO,ESTOP,ELA,ELO,M,N,E,G FROM
(
SELECT y.ID,BSTOP,BLA,BLO,ESTOP,ELA,ELO,M,N,E,G,ROW_NUMBER() OVER(PARTITION BY RGN,BSTOP,BLA,BLO,ESTOP,ELA,ELO ORDER BY LEN(y.ROUTE_NAME) ASC) RANG from
(
SELECT RGN,BSTOP,BLA,BLO,ESTOP,ELA,ELO,isnull(M,0) M,isnull(N,0) N,isnull(E,0) E,isnull(G,0) G FROM
(
SELECT DAYPART,RGN,BSTOP,BLA,BLO,ESTOP,ELA,ELO, SUM(AMOUNT) AMOUNT FROM
(
SELECT DAYPART,RGN,BSTOP,BLA,BLO,ECITY ESTOP,LA ELA,LO ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BCITY BSTOP,LA BLA,LO BLO,ESTOP,ECITY,ELA,ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,b.STOP_NAME BSTOP,b.CITY_NUMBER BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BGN,EGN,AMOUNT,b.ID as BID,c.ID as EID,
ROW_NUMBER() OVER(PARTITION BY DAYPART,RGN,BGN,EGN 
ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE)+(b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG
from
(
SELECT DAYPART,RGN,BGN,EGN,SUM(AMOUNT) AMOUNT FROM
(
select DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_DS_TRANSACT_AGG a join ULTIMATE_ROUTES b 
on (a.IdDataSource=b.SOURCE_REGION and a.IdRoute=b.SOURCE_CODE and b.SOURCE=2)
join ULTIMATE_STOPS c on (c.SOURCE_REGION=a.IdDataSource and c.SOURCE_CODE=a.BSTOP and c.SOURCE=2)
join ULTIMATE_STOPS d on (d.SOURCE_REGION=a.IdDataSource and d.SOURCE_CODE=a.ESTOP and d.SOURCE=2)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
UNION ALL
select 
CASE 
      WHEN DHOR >= 6 AND DHOR<10 THEN 'M' 
      WHEN DHOR >= 10 AND DHOR<16 THEN 'N' 
      WHEN DHOR >= 16 AND DHOR<20 THEN 'E' 
      WHEN DHOR >= 20 OR DHOR<6 THEN 'G' 
END DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_RISE_TRANSACT a join ULTIMATE_ROUTES b 
on (a.ROUTE_ID=b.ID)
join ULTIMATE_STOPS c on (c.ID=a.BGN)
join ULTIMATE_STOPS d on (d.ID=a.EGN)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
) x GROUP BY DAYPART,RGN,BGN,EGN
) x 
join ULTIMATE_STOPS b on (BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (BID=b.ID)
join ULTIMATE_STOPS c on (EID=c.ID)
WHERE RANG=1
) x
join (SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS WHERE CITY_NUMBER not like '' GROUP BY CITY_NUMBER) y
on (x.BCITY like y.CITY_NUMBER)
WHERE BCITY not like ''
UNION ALL
SELECT DAYPART,RGN,BSTOP,BLA,BLO,ESTOP,ECITY,ELA,ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,b.STOP_NAME BSTOP,b.CITY_NUMBER BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BGN,EGN,AMOUNT,b.ID as BID,c.ID as EID,
ROW_NUMBER() OVER(PARTITION BY DAYPART,RGN,BGN,EGN 
ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE)+(b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG
from
(
SELECT DAYPART,RGN,BGN,EGN,SUM(AMOUNT) AMOUNT FROM
(
select DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_DS_TRANSACT_AGG a join ULTIMATE_ROUTES b 
on (a.IdDataSource=b.SOURCE_REGION and a.IdRoute=b.SOURCE_CODE and b.SOURCE=2)
join ULTIMATE_STOPS c on (c.SOURCE_REGION=a.IdDataSource and c.SOURCE_CODE=a.BSTOP and c.SOURCE=2)
join ULTIMATE_STOPS d on (d.SOURCE_REGION=a.IdDataSource and d.SOURCE_CODE=a.ESTOP and d.SOURCE=2)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
UNION ALL
select 
CASE 
      WHEN DHOR >= 6 AND DHOR<10 THEN 'M' 
      WHEN DHOR >= 10 AND DHOR<16 THEN 'N' 
      WHEN DHOR >= 16 AND DHOR<20 THEN 'E' 
      WHEN DHOR >= 20 OR DHOR<6 THEN 'G' 
END DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_RISE_TRANSACT a join ULTIMATE_ROUTES b 
on (a.ROUTE_ID=b.ID)
join ULTIMATE_STOPS c on (c.ID=a.BGN)
join ULTIMATE_STOPS d on (d.ID=a.EGN)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
) x GROUP BY DAYPART,RGN,BGN,EGN
) x 
join ULTIMATE_STOPS b on (BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (BID=b.ID)
join ULTIMATE_STOPS c on (EID=c.ID)
WHERE RANG=1
) x
WHERE BCITY like ''
) x
join (SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS WHERE CITY_NUMBER not like '' GROUP BY CITY_NUMBER) y
on (x.ECITY like y.CITY_NUMBER)
WHERE ECITY not like ''


UNION ALL


SELECT DAYPART,RGN,BSTOP,BLA,BLO,ESTOP,ELA,ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BCITY BSTOP,LA BLA,LO BLO,ESTOP,ECITY,ELA,ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,b.STOP_NAME BSTOP,b.CITY_NUMBER BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BGN,EGN,AMOUNT,b.ID as BID,c.ID as EID,
ROW_NUMBER() OVER(PARTITION BY DAYPART,RGN,BGN,EGN 
ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE)+(b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG
from
(
SELECT DAYPART,RGN,BGN,EGN,SUM(AMOUNT) AMOUNT FROM
(
select DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_DS_TRANSACT_AGG a join ULTIMATE_ROUTES b 
on (a.IdDataSource=b.SOURCE_REGION and a.IdRoute=b.SOURCE_CODE and b.SOURCE=2)
join ULTIMATE_STOPS c on (c.SOURCE_REGION=a.IdDataSource and c.SOURCE_CODE=a.BSTOP and c.SOURCE=2)
join ULTIMATE_STOPS d on (d.SOURCE_REGION=a.IdDataSource and d.SOURCE_CODE=a.ESTOP and d.SOURCE=2)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
UNION ALL
select 
CASE 
      WHEN DHOR >= 6 AND DHOR<10 THEN 'M' 
      WHEN DHOR >= 10 AND DHOR<16 THEN 'N' 
      WHEN DHOR >= 16 AND DHOR<20 THEN 'E' 
      WHEN DHOR >= 20 OR DHOR<6 THEN 'G' 
END DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_RISE_TRANSACT a join ULTIMATE_ROUTES b 
on (a.ROUTE_ID=b.ID)
join ULTIMATE_STOPS c on (c.ID=a.BGN)
join ULTIMATE_STOPS d on (d.ID=a.EGN)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
) x GROUP BY DAYPART,RGN,BGN,EGN
) x 
join ULTIMATE_STOPS b on (BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (BID=b.ID)
join ULTIMATE_STOPS c on (EID=c.ID)
WHERE RANG=1
) x
join (SELECT CITY_NUMBER, AVG(LATITUDE) LA, AVG(LONGITUDE) LO FROM ULTIMATE_STOPS WHERE CITY_NUMBER not like '' GROUP BY CITY_NUMBER) y
on (x.BCITY like y.CITY_NUMBER)
WHERE BCITY not like ''
UNION ALL
SELECT DAYPART,RGN,BSTOP,BLA,BLO,ESTOP,ECITY,ELA,ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,b.STOP_NAME BSTOP,b.CITY_NUMBER BCITY,b.LATITUDE BLA,b.LONGITUDE BLO,
c.STOP_NAME ESTOP,c.CITY_NUMBER ECITY,c.LATITUDE ELA,c.LONGITUDE ELO,AMOUNT FROM
(
SELECT DAYPART,RGN,BGN,EGN,AMOUNT,b.ID as BID,c.ID as EID,
ROW_NUMBER() OVER(PARTITION BY DAYPART,RGN,BGN,EGN 
ORDER BY (b.LATITUDE-c.LATITUDE)*(b.LATITUDE-c.LATITUDE)+(b.LONGITUDE-c.LONGITUDE)*(b.LONGITUDE-c.LONGITUDE) ASC) RANG
from
(
SELECT DAYPART,RGN,BGN,EGN,SUM(AMOUNT) AMOUNT FROM
(
select DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_DS_TRANSACT_AGG a join ULTIMATE_ROUTES b 
on (a.IdDataSource=b.SOURCE_REGION and a.IdRoute=b.SOURCE_CODE and b.SOURCE=2)
join ULTIMATE_STOPS c on (c.SOURCE_REGION=a.IdDataSource and c.SOURCE_CODE=a.BSTOP and c.SOURCE=2)
join ULTIMATE_STOPS d on (d.SOURCE_REGION=a.IdDataSource and d.SOURCE_CODE=a.ESTOP and d.SOURCE=2)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
UNION ALL
select 
CASE 
      WHEN DHOR >= 6 AND DHOR<10 THEN 'M' 
      WHEN DHOR >= 10 AND DHOR<16 THEN 'N' 
      WHEN DHOR >= 16 AND DHOR<20 THEN 'E' 
      WHEN DHOR >= 20 OR DHOR<6 THEN 'G' 
END DAYPART, b.GROUP_NUMBER RGN,c.GROUP_NUMBER BGN,d.GROUP_NUMBER EGN,AMOUNT from ULTIMATE_RISE_TRANSACT a join ULTIMATE_ROUTES b 
on (a.ROUTE_ID=b.ID)
join ULTIMATE_STOPS c on (c.ID=a.BGN)
join ULTIMATE_STOPS d on (d.ID=a.EGN)
where (1=1 or (b.GROUP_NUMBER in (109))) and ((DMON = 4 and DDAY in (3,4,5,6,7,8,9)) or (DMON = 7 and DDAY in (17,18,19,20,21,22,23)))
) x GROUP BY DAYPART,RGN,BGN,EGN
) x 
join ULTIMATE_STOPS b on (BGN=b.GROUP_NUMBER and b.SOURCE=1)
join ULTIMATE_STOPS c on (EGN=c.GROUP_NUMBER and c.SOURCE=1)
) x 
join ULTIMATE_STOPS b on (BID=b.ID)
join ULTIMATE_STOPS c on (EID=c.ID)
WHERE RANG=1
) x
WHERE BCITY like ''
) x
WHERE ECITY like ''
) x GROUP BY DAYPART,RGN,BSTOP,BLA,BLO,ESTOP,ELA,ELO
) x
PIVOT
(
SUM(AMOUNT)
FOR DAYPART in (M,N,E,G)
) y
) x JOIN ULTIMATE_ROUTES y on (x.RGN=y.GROUP_NUMBER)
) x JOIN ULTIMATE_ROUTES y on (x.ID=y.ID) WHERE RANG=1