--TIMETABLE
SELECT 
CASE
WHEN RNAME LIKE N'П %' or RNAME LIKE N'М %' THEN SUBSTRING(RNAME,3,LEN(RNAME))
WHEN RNAME LIKE N'ПН %' or RNAME LIKE N'МН %' THEN SUBSTRING(RNAME,4,LEN(RNAME))
WHEN RNAME LIKE N'Персп 2П %' or RNAME LIKE N'Персп 2М %' THEN SUBSTRING(RNAME,10,LEN(RNAME))
WHEN RNAME LIKE N'Персп %' THEN SUBSTRING(RNAME,7,LEN(RNAME))
ELSE RNAME
END
RNAME, 
CASE
WHEN SNAME LIKE N'"%"' THEN REPLACE(SUBSTRING(SNAME,2,LEN(SNAME)-2),'""','"')
ELSE SNAME
END
SNAME, ISNULL(REGNO,'-') REGNO, DIR, SEASON, COND, 
ISNULL(STRING_AGG(ARR,'; ')  WITHIN GROUP (ORDER BY FULL_ARR ASC),'-') ARR, 
ISNULL(STR(STAY),'-') STAY, 
ISNULL(STRING_AGG(DEP,'; ') WITHIN GROUP (ORDER BY FULL_ARR ASC),'-') DEP 
FROM (
SELECT RNAME,b.ALLDIST, b.SNAME,b.SID, CASE WHEN a.DIR like '>' THEN N'Прямое направление' ELSE N'Обратное направление' END DIR, SEASON, COND, 
CASE WHEN b.PREVDIST=0  THEN NULL ELSE SUBSTRING(CONCAT(DATEADD(SS,60*(IND-2)+3600.0*ALLDIST/SPEED,DEP),''),1,5) END ARR,
CASE WHEN b.PREVDIST=0 or b.NEXTDIST=0  THEN NULL ELSE 1 END STAY,
CASE WHEN b.NEXTDIST=0  THEN NULL ELSE SUBSTRING(CONCAT(DATEADD(SS,60*(IND-1)+3600.0*ALLDIST/SPEED,DEP),''),1,5) END DEP,
SUBSTRING(CONCAT(DATEADD(SS,60*(IND-2)+3600.0*ALLDIST/SPEED,DEP),''),1,5) FULL_ARR
FROM (
SELECT distinct RNAME,
SPEED,  
DIR,PERIOD,DEP,COND,SINCE,TILL,PROLONG,SEASON
FROM PRE_RASP
) a join GOTHROUGH b on (a.RNAME like b.ROUTE_N_NAME and a.DIR=b.DIR) WHERE PERIOD = 0
) x left join (select CODE, CONCAT('0',RegNo) REGNO from RegNos) y on (x.SID=y.CODE)
GROUP BY RNAME, SNAME, REGNO, DIR, SEASON, COND, STAY, ALLDIST
ORDER BY RNAME ASC,DIR DESC, SEASON, ALLDIST ASC,SNAME ASC,COND ASC
--ORDER BY SNAME ASC,RNAME ASC,DIR DESC,COND ASC

SELECT * FROM GOTHROUGH WHERE ROUTE_N_NAME LIKE N'%М 534 Бирск - Уфа ч/з западную развилку%'
--UPDATE PRE_RASP SET SPEED = 41 WHERE RNAME LIKE N'%114а Уфа (Дема) - д. Новомихайловка%'
SELECT * FROM PRE_RASP WHERE RNAME LIKE N'%114а Уфа (Дема) - д. Новомихайловка%'
--INSERT INTO PRE_RASP VALUES (N'П 116 Нефтекамск - Амзя',43,'>',0,'11:50',N'ПН-ВС',NULL,NULL,NULL,N'Круглогодично')

--UPDATE PRE_RASP SET SPEED = b.SPEED FROM PRE_RASP a JOIN SPEED_UPDATE b on (RNAME like CONCAT('%',b.NAME,'%'))
SELECT a.ROUTE_N_NAME,a.SNAME,b.SNAME FROM
(SELECT ROUTE_N_NAME, DIR, SNAME FROM GOTHROUGH WHERE DIR like '>' and IND=1) a
full join (SELECT ROUTE_N_NAME, DIR, SNAME FROM GOTHROUGH WHERE DIR like '<' and IND=1) b
on (a.ROUTE_N_NAME like b.ROUTE_N_NAME);

--INTERVALS
SELECT RNAME,COND,SEASON,SNAME,ISNULL(REGNO,'-') REGNO,t, INTER,PERIOD_F,PERIOD_B,SINCE_F,SINCE_B,TILL_F,TILL_B FROM (
SELECT distinct
CASE
WHEN RNAME LIKE N'П %' or RNAME LIKE N'М %' THEN SUBSTRING(RNAME,3,LEN(RNAME))
WHEN RNAME LIKE N'ПН %' or RNAME LIKE N'МН %' THEN SUBSTRING(RNAME,4,LEN(RNAME))
WHEN RNAME LIKE N'Персп 2П %' or RNAME LIKE N'Персп 2М %' THEN SUBSTRING(RNAME,10,LEN(RNAME))
WHEN RNAME LIKE N'Персп %' THEN SUBSTRING(RNAME,7,LEN(RNAME))
ELSE RNAME
END
RNAME,
COND,
SEASON,
CASE
WHEN SNAME LIKE N'"%"' THEN REPLACE(SUBSTRING(SNAME,2,LEN(SNAME)-2),'""','"')
ELSE SNAME
END
SNAME,
SID,
ALLDIST,
DIR,
t,
CASE 
WHEN ISNULL(SINCE_F,SINCE_B)<=ISNULL(SINCE_B,SINCE_F) AND ISNULL(TILL_F,TILL_B)>=ISNULL(TILL_B,TILL_F) THEN CONCAT(SUBSTRING(CONCAT(CAST(dbo.FLOORTIME(ISNULL(SINCE_F,SINCE_B),5) AS TIME),''),1,5),' - ',SUBSTRING(CONCAT(CAST(dbo.CEILINGTIME(ISNULL(TILL_F,TILL_B),5) AS TIME),''),1,5))
WHEN ISNULL(SINCE_F,SINCE_B)>=ISNULL(SINCE_B,SINCE_F) AND ISNULL(TILL_F,TILL_B)>=ISNULL(TILL_B,TILL_F) THEN CONCAT(SUBSTRING(CONCAT(CAST(dbo.FLOORTIME(ISNULL(SINCE_B,SINCE_F),5) AS TIME),''),1,5),' - ',SUBSTRING(CONCAT(CAST(dbo.CEILINGTIME(ISNULL(TILL_F,TILL_B),5) AS TIME),''),1,5))
WHEN ISNULL(SINCE_F,SINCE_B)<=ISNULL(SINCE_B,SINCE_F) AND ISNULL(TILL_F,TILL_B)<=ISNULL(TILL_B,TILL_F) THEN CONCAT(SUBSTRING(CONCAT(CAST(dbo.FLOORTIME(ISNULL(SINCE_F,SINCE_B),5) AS TIME),''),1,5),' - ',SUBSTRING(CONCAT(CAST(dbo.CEILINGTIME(ISNULL(TILL_B,TILL_F),5) AS TIME),''),1,5))
WHEN ISNULL(SINCE_F,SINCE_B)>=ISNULL(SINCE_B,SINCE_F) AND ISNULL(TILL_F,TILL_B)<=ISNULL(TILL_B,TILL_F) THEN CONCAT(SUBSTRING(CONCAT(CAST(dbo.FLOORTIME(ISNULL(SINCE_B,SINCE_F),5) AS TIME),''),1,5),' - ',SUBSTRING(CONCAT(CAST(dbo.CEILINGTIME(ISNULL(TILL_B,TILL_F),5) AS TIME),''),1,5))
END INTER,
CONCAT(PERIOD_F,'') PERIOD_F, CONCAT(PERIOD_B,'') PERIOD_B,
SUBSTRING(CONCAT(DATEADD(MI,CASE WHEN DATEPART(SS,SINCE_F)<30 THEN 0 ELSE 1 END,SINCE_F),''),1,5) SINCE_F,
SUBSTRING(CONCAT(DATEADD(MI,CASE WHEN DATEPART(SS,SINCE_B)<30 THEN 0 ELSE 1 END,SINCE_B),''),1,5) SINCE_B,
SUBSTRING(CONCAT(DATEADD(MI,CASE WHEN DATEPART(SS,TILL_F)<30 THEN 0 ELSE 1 END,TILL_F),''),1,5) TILL_F,
SUBSTRING(CONCAT(DATEADD(MI,CASE WHEN DATEPART(SS,TILL_B)<30 THEN 0 ELSE 1 END,TILL_B),''),1,5) TILL_B
FROM (
SELECT t,ALLDIST,DIR,RNAME,COND, SEASON,SNAME,SID,
CASE WHEN DIR LIKE '>' THEN PERIOD ELSE NULL END PERIOD_F,
CASE WHEN DIR LIKE '<' THEN PERIOD ELSE NULL END PERIOD_B,
CASE WHEN DIR LIKE '>' THEN SINCE ELSE NULL END SINCE_F,
CASE WHEN DIR LIKE '<' THEN SINCE ELSE NULL END SINCE_B,
CASE WHEN DIR LIKE '>' THEN TILL ELSE NULL END TILL_F,
CASE WHEN DIR LIKE '<' THEN TILL ELSE NULL END TILL_B
FROM
(
SELECT b.ALLDIST,t,RNAME,SNAME,SID,PERIOD, a.DIR,DATEADD(SS,3600.0*ALLDIST/SPEED,SINCE) SINCE, DATEADD(SS,3600.0*ALLDIST/SPEED,TILL) TILL, a.COND, a.SEASON
FROM 
(
SELECT 0 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG=PERIOD 
UNION
select 1 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE,CAST(DATEADD(MI,-PROLONG,CAST('07:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('07:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('07:00' as time) SINCE,TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('07:00' as time) and TILL < CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('07:00' as time) and TILL < CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, CAST(DATEADD(MI,-PERIOD,CAST('10:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('07:00' as time) and SINCE < CAST('10:00' as time) and TILL >= CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('07:00' as time) SINCE, CAST(DATEADD(MI,-PERIOD,CAST('10:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('10:00' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('10:00' as time) SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('10:00' as time) and TILL >= CAST('10:00' as time) and TILL < CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('10:00' as time) SINCE, CAST(DATEADD(MI,-PROLONG,CAST('16:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('10:00' as time) and TILL >= CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE, CAST(DATEADD(MI,-PROLONG,CAST('16:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('10:00' as time) and SINCE < CAST('16:30' as time)and TILL >= CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('10:00' as time) and TILL < CAST('16:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('16:30' as time) SINCE,TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('16:30' as time) and TILL >= CAST('16:30' as time) and TILL < CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('16:30' as time) and TILL < CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, CAST(DATEADD(MI,-PERIOD,CAST('19:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('16:30' as time) and SINCE < CAST('19:30' as time) and TILL >= CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('16:30' as time) SINCE, CAST(DATEADD(MI,-PERIOD,CAST('19:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('16:30' as time) and TILL >= CAST('19:30' as time)
UNION
select 5 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('19:30' as time) SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('19:30' as time) and TILL >= CAST('19:30' as time)
) a 
join GOTHROUGH b on (a.RNAME like b.ROUTE_N_NAME and a.DIR=b.DIR) WHERE PERIOD > 0 and a.DIR like '>'
UNION ALL
SELECT b.ALLDIST,t,RNAME,SNAME,SID,PERIOD, a.DIR,DATEADD(SS,3600.0*ALLDIST/SPEED,SINCE) SINCE, DATEADD(SS,3600.0*ALLDIST/SPEED,TILL) TILL, a.COND, a.SEASON
FROM 
(
SELECT 0 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG=PERIOD 
UNION
select 1 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE,CAST(DATEADD(MI,-PROLONG,CAST('07:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('07:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('07:00' as time) SINCE,TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('07:00' as time) and TILL < CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('07:00' as time) and TILL < CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, CAST(DATEADD(MI,-PERIOD,CAST('10:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('07:00' as time) and SINCE < CAST('10:00' as time) and TILL >= CAST('10:00' as time)
UNION
select 2 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('07:00' as time) SINCE, CAST(DATEADD(MI,-PERIOD,CAST('10:00' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('07:00' as time) and TILL >= CAST('10:00' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('10:00' as time) SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('10:00' as time) and TILL >= CAST('10:00' as time) and TILL < CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('10:00' as time) SINCE, CAST(DATEADD(MI,-PROLONG,CAST('16:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('10:00' as time) and TILL >= CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE, CAST(DATEADD(MI,-PROLONG,CAST('16:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('10:00' as time) and SINCE < CAST('16:30' as time)and TILL >= CAST('16:30' as time)
UNION
select 3 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('10:00' as time) and TILL < CAST('16:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('16:30' as time) SINCE,TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('16:30' as time) and TILL >= CAST('16:30' as time) and TILL < CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('16:30' as time) and TILL < CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, SINCE, CAST(DATEADD(MI,-PERIOD,CAST('19:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE >= CAST('16:30' as time) and SINCE < CAST('19:30' as time) and TILL >= CAST('19:30' as time)
UNION
select 4 t, RNAME, SPEED, DIR, PERIOD, COND, SEASON, CAST('16:30' as time) SINCE, CAST(DATEADD(MI,-PERIOD,CAST('19:30' as time)) as time) TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('16:30' as time) and TILL >= CAST('19:30' as time)
UNION
select 5 t, RNAME, SPEED, DIR, PROLONG, COND, SEASON, CAST('19:30' as time) SINCE, TILL from PRE_RASP a WHERE PERIOD > 0 and PROLONG!=PERIOD and SINCE < CAST('19:30' as time) and TILL >= CAST('19:30' as time)
) a 
join GOTHROUGH b on (a.RNAME like b.ROUTE_N_NAME and a.DIR like b.DIR) WHERE PERIOD > 0 and a.DIR like '<'
)
x
)
x
)
x left join (select CODE, CONCAT('0',RegNo) REGNO from RegNos) y on (x.SID=y.CODE)
--WHERE RNAME Like N'%Новомихайловка%'
ORDER BY RNAME,COND,DIR,ALLDIST,SNAME,t,SINCE_F,SINCE_B
